Repository Team-Offroad/Offroad-server, pull requests merged in 2024-08, with the labels that each got.

#163 [feat] : 유저가 보유한 캐릭터 목록 조회 API 구현 및 GOOGLE 소셜로그인 시 플랫폼 저장
  offroad-api/src/main/java/site/offload/api/character/service/GainedCharacterService.java
  offroad-api/src/main/java/site/offload/api/member/controller/MemberController.java
  offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharacterResponse.java
  offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharactersResponse.java
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
  offroad-api/src/main/java/site/offload/api/member/usecase/SocialLoginUseCase.java
  offroad-api/src/main/resources/application-local.yaml
  offroad-api/src/test/java/site/offload/api/character/CharacterEntityFixtureCreator.java
  offroad-api/src/test/java/site/offload/api/character/service/GainedCharacterServiceTest.java
  offroad-api/src/test/java/site/offload/api/character/usecase/GainedCharacterUseCaseTest.java
  offroad-db/src/main/java/site/offload/db/character/entity/CharacterEntity.java
  offroad-db/src/main/java/site/offload/db/character/repository/GainedCharacterRepository.java
  offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java
Labels: Feature

#170 chore: 칭호 목록 업데이트
  offroad-enum/src/main/java/site/offload/enums/emblem/Emblem.java
Labels: Chore

#171 fix: 칭호 중복 수정
  offroad-enum/src/main/java/site/offload/enums/emblem/Emblem.java
Labels: Chore

#175 [fix] : 캐릭터 목록 조회 시 응답 값 수정
  offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharacterResponse.java
  offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharactersResponse.java
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
  offroad-api/src/test/java/site/offload/api/character/service/GainedCharacterServiceTest.java
  offroad-api/src/test/java/site/offload/api/character/usecase/GainedCharacterUseCaseTest.java
  offroad-api/src/test/java/site/offload/api/charactermotion/service/CharacterMotionServiceTest.java
  offroad-api/src/test/java/site/offload/api/charactermotion/usecase/CharacterMotionUseCaseTest.java
  offroad-api/src/test/java/site/offload/api/fixture/CharacterEntityFixtureCreator.java
  offroad-api/src/test/java/site/offload/api/member/usecase/AuthAdventureUseCaseTest.java
  offroad-db/src/main/java/site/offload/db/character/entity/CharacterEntity.java
Labels: Chore

#179 feat: 퀘스트 목록 조회 api 구현
  offroad-api/src/main/java/site/offload/api/quest/controller/QuestController.java
  offroad-api/src/main/java/site/offload/api/quest/controller/QuestControllerSwagger.java
  offroad-api/src/main/java/site/offload/api/quest/dto/request/QuestDetailListRequest.java
  offroad-api/src/main/java/site/offload/api/quest/dto/response/QuestDetailListResponse.java
  offroad-api/src/main/java/site/offload/api/quest/dto/response/QuestDetailResponse.java
  offroad-api/src/main/java/site/offload/api/quest/service/CompleteQuestService.java
  offroad-api/src/main/java/site/offload/api/quest/service/ProceedingQuestService.java
  offroad-api/src/main/java/site/offload/api/quest/service/QuestService.java
  offroad-api/src/main/java/site/offload/api/quest/usecase/QuestUseCase.java
  offroad-api/src/test/java/site/offload/api/fixture/CompleteQuestEntityFixture.java
  offroad-api/src/test/java/site/offload/api/fixture/ProceedingQuestEntityFixture.java
  offroad-api/src/test/java/site/offload/api/quest/service/CompleteQuestServiceTest.java
  offroad-api/src/test/java/site/offload/api/quest/service/ProceedingQuestServiceTest.java
  offroad-api/src/test/java/site/offload/api/quest/service/QuestServiceTest.java
  offroad-api/src/test/java/site/offload/api/quest/usecase/QuestUseCaseTest.java
  offroad-db/src/main/java/site/offload/db/quest/entity/QuestEntity.java
  offroad-db/src/main/java/site/offload/db/quest/repository/CompleteQuestRepository.java
  offroad-db/src/main/java/site/offload/db/quest/repository/ProceedingQuestRepository.java
  offroad-db/src/main/java/site/offload/db/quest/repository/QuestRepository.java
  offroad-enum/src/main/java/site/offload/enums/place/PlaceCategory.java
  offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java
Labels: Feature

#187 refactor: 장소 조회 API 리팩토링
  offroad-api/build.gradle
  offroad-api/src/main/java/site/offload/api/place/controller/PlaceController.java
  offroad-api/src/main/java/site/offload/api/place/controller/PlaceControllerSwagger.java
  offroad-api/src/main/java/site/offload/api/place/dto/request/RegisteredPlacesRequest.java
  offroad-api/src/main/java/site/offload/api/place/service/PlaceService.java
  offroad-api/src/main/java/site/offload/api/place/service/VisitedPlaceService.java
  offroad-api/src/main/java/site/offload/api/place/usecase/PlaceUseCase.java
  offroad-api/src/main/java/site/offload/api/place/usecase/PlaceUsecase.java
  offroad-api/src/test/java/site/offload/api/place/service/PlaceEntityServiceTest.java
  offroad-db/src/main/java/site/offload/db/place/repository/PlaceRepository.java
  offroad-db/src/main/java/site/offload/db/place/repository/VisitedPlaceRepository.java
Labels: Refactor

#183 feat: 유저 탈퇴 API 구현
  offroad-api/build.gradle
  offroad-api/src/main/java/site/offload/api/OffloadserverApiApplication.java
  offroad-api/src/main/java/site/offload/api/character/service/GainedCharacterService.java
  offroad-api/src/main/java/site/offload/api/config/WebConfig.java
  offroad-api/src/main/java/site/offload/api/interceptor/MemberStatusInterceptor.java
  offroad-api/src/main/java/site/offload/api/member/controller/MemberController.java
  offroad-api/src/main/java/site/offload/api/member/dto/request/MemberDeleteRequest.java
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
  offroad-api/src/main/java/site/offload/api/member/usecase/SocialLoginUseCase.java
  offroad-api/src/main/java/site/offload/api/quest/service/QuestRewardService.java
  offroad-api/src/main/java/site/offload/api/util/MemberDeleteLoggingUtil.java
  offroad-api/src/test/java/site/offload/api/character/service/CharacterServiceTest.java
  offroad-api/src/test/java/site/offload/api/interceptor/MemberStatusInterceptorTest.java
  offroad-api/src/test/java/site/offload/api/member/usecase/MemberUseCaseTest.java
  offroad-api/src/test/java/site/offload/api/questReward/usecase/QuestRewardUseCaseTest.java
  offroad-batch/build.gradle
  offroad-batch/src/main/java/site/offload/batch/member/MemberBatchService.java
  offroad-cache/src/main/java/site/offload/cache/config/RedisRepository.java
  offroad-cache/src/main/java/site/offload/cache/member/service/MemberStatusCacheService.java
  offroad-db/src/main/java/site/offload/db/coupon/entity/GainedCouponEntity.java
  offroad-db/src/main/java/site/offload/db/emblem/repository/GainedEmblemRepository.java
  offroad-db/src/main/java/site/offload/db/member/entity/MemberEntity.java
  offroad-db/src/main/java/site/offload/db/member/repository/MemberRepository.java
  offroad-enum/src/main/java/site/offload/enums/member/MemberStatus.java
  offroad-enum/src/main/java/site/offload/enums/response/CustomErrorCode.java
  offroad-enum/src/main/java/site/offload/enums/response/ErrorMessage.java
  offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java
  settings.gradle
Labels: Feature
