Repository Team-Offroad/Offroad-server, pull requests merged in 2024-06, with the labels that each got.

#7 [docs] Update issue templates
  .github/ISSUE_TEMPLATE/offroad-issue-template.md
Labels: Setting

#6 [feat] create pull_request_template.md
  pull_request_template.md
Labels: Setting

#10 [feat] Docker 기반 ci/cd 구축
  .github/workflows/dev-CD.yaml
  .github/workflows/dev-CI.yaml
  .gitignore
  Dockerfile-dev
  build.gradle
  gradlew.bat
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
Labels: Feature, Setting

#16 [feat] README.md 업데이트
  README.md
Labels: Docs
