Repository Team-Offroad/Offroad-server, pull requests merged in 2024-07, with the labels that each got.

#17 [feat] API 응답 포맷 세팅
  src/main/java/site/offload/offloadserver/common/api/message/ErrorMessage.java
  src/main/java/site/offload/offloadserver/common/api/message/SuccessMessage.java
  src/main/java/site/offload/offloadserver/common/api/response/APIErrorResponse.java
  src/main/java/site/offload/offloadserver/common/api/response/APISuccessResponse.java
  src/main/java/site/offload/offloadserver/common/temp
Labels: Feature

#18 [feat] : Swgger 세팅
  build.gradle
  src/main/java/site/offload/offloadserver/HealthCheckController.java
  src/main/java/site/offload/offloadserver/HealthCheckControllerSwagger.java
  src/main/java/site/offload/offloadserver/common/api/config/SwaggerConfig.java
Labels: Feature, Setting

#9 [feat] SpringBoot -> Discord 웹훅 연결
  src/main/java/site/offload/offloadserver/api/exception/RestClientException.java
  src/main/java/site/offload/offloadserver/api/exception/RestClientUseCase.java
  src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
  src/main/java/site/offload/offloadserver/external/discord/DiscordService.java
  src/main/java/site/offload/offloadserver/external/discord/DiscordWebhookRequest.java
  src/main/java/site/offload/offloadserver/external/discord/Embed.java
Labels: Feature, Setting

#36 [fix] : ErrorAPIResponse 오류 해결
  src/main/java/site/offload/offloadserver/api/message/CustomErrorCode.java
  src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
Labels: 🐞 Bug

#42 [feat] 토큰 재발급 API
  src/main/java/site/offload/offloadserver/api/member/controller/TokenController.java
  src/main/java/site/offload/offloadserver/api/member/controller/TokenControllerSwagger.java
  src/main/java/site/offload/offloadserver/api/member/dto/response/TokenReissueResponse.java
  src/main/java/site/offload/offloadserver/api/member/service/MemberUseCase.java
  src/main/java/site/offload/offloadserver/api/message/CustomErrorCode.java
  src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
  src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java
Labels: Feature

#43 [fix] 반환값에 캐릭터 이름 추가
  src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java
  src/main/java/site/offload/offloadserver/api/member/dto/MemberAdventureInformationResponse.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
Labels: HOTFIX

#45 [fix] MemberUseCase 클래스 중복 수정
  src/main/java/site/offload/offloadserver/api/member/controller/TokenController.java
  src/main/java/site/offload/offloadserver/api/member/service/MemberUseCase.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
Labels: Chore

#50 [feat] 칭호 변경 API
  src/main/java/site/offload/offloadserver/api/emblem/controller/EmblemControllSwawgger.java
  src/main/java/site/offload/offloadserver/api/emblem/controller/EmblemController.java
  src/main/java/site/offload/offloadserver/api/emblem/dto/request/UpdateCurrentEmblemRequest.java
  src/main/java/site/offload/offloadserver/api/emblem/service/GainedEmblemService.java
  src/main/java/site/offload/offloadserver/api/emblem/usecase/EmblemUseCase.java
  src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java
  src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java
  src/main/java/site/offload/offloadserver/api/member/dto/request/MemberAdventureInformationRequest.java
  src/main/java/site/offload/offloadserver/api/member/dto/response/MemberAdventureInformationResponse.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/api/message/CustomErrorCode.java
  src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
  src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java
  src/main/java/site/offload/offloadserver/db/emblem/entity/Emblem.java
  src/main/java/site/offload/offloadserver/db/emblem/repository/GainedEmblemRepository.java
  src/main/java/site/offload/offloadserver/db/member/entity/Member.java
Labels: Feature

#53 [feat] 칭호 조회 API
  src/main/java/site/offload/offloadserver/api/emblem/controller/EmblemControllSwawgger.java
  src/main/java/site/offload/offloadserver/api/emblem/controller/EmblemController.java
  src/main/java/site/offload/offloadserver/api/emblem/dto/response/GainedEmblemListResponse.java
  src/main/java/site/offload/offloadserver/api/emblem/dto/response/GainedEmblemResponse.java
  src/main/java/site/offload/offloadserver/api/emblem/service/GainedEmblemService.java
  src/main/java/site/offload/offloadserver/api/emblem/usecase/EmblemUseCase.java
  src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java
  src/main/java/site/offload/offloadserver/db/emblem/entity/GainedEmblem.java
  src/main/java/site/offload/offloadserver/db/emblem/repository/GainedEmblemRepository.java
Labels: Feature

#57 [feat] 캐릭터 정보 조회 API
  src/main/java/site/offload/offloadserver/api/character/controller/CharacterController.java
  src/main/java/site/offload/offloadserver/api/character/controller/CharacterControllerSwagger.java
  src/main/java/site/offload/offloadserver/api/character/dto/response/CharacterListResponse.java
  src/main/java/site/offload/offloadserver/api/character/dto/response/CharacterResponse.java
  src/main/java/site/offload/offloadserver/api/character/service/CharacterService.java
  src/main/java/site/offload/offloadserver/api/character/usecase/CharacterUseCase.java
  src/main/java/site/offload/offloadserver/api/charactermotion/service/CharacterMotionService.java
  src/main/java/site/offload/offloadserver/api/charactermotion/service/GainedCharacterMotionService.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java
  src/main/java/site/offload/offloadserver/db/member/embeddable/Birthday.java
  src/main/java/site/offload/offloadserver/db/member/entity/Member.java
Labels: Feature

#59 [fix] security 수정
  src/main/java/site/offload/offloadserver/common/jwt/JwtTokenProvider.java
Labels: Refactor

#60 [fix] 필터체인 수정
  src/main/java/site/offload/offloadserver/common/auth/SecurityConfig.java
Labels: 🐞 Bug

#68 [fix] : 구글 소셜 로그인
  build.gradle
  src/main/java/site/offload/offloadserver/OffloadserverApplication.java
  src/main/java/site/offload/offloadserver/common/auth/SecurityConfig.java
  src/main/java/site/offload/offloadserver/common/jwt/JwtTokenProvider.java
  src/main/java/site/offload/offloadserver/external/oauth/google/GoogleSocialLoginService.java
  src/main/java/site/offload/offloadserver/external/oauth/google/request/GoogleApiClient.java
  src/main/java/site/offload/offloadserver/external/oauth/google/request/GoogleAuthApiClient.java
  src/main/java/site/offload/offloadserver/external/oauth/google/response/GoogleAuthResponse.java
  src/main/java/site/offload/offloadserver/external/oauth/google/response/GoogleInfoResponse.java
Labels: Chore

#70 [fix] 칭호 조회, 업데이트 api 수정
  src/main/java/site/offload/offloadserver/api/emblem/dto/request/UpdateCurrentEmblemRequest.java
  src/main/java/site/offload/offloadserver/api/emblem/service/GainedEmblemService.java
  src/main/java/site/offload/offloadserver/api/emblem/usecase/EmblemUseCase.java
  src/main/java/site/offload/offloadserver/api/message/CustomErrorCode.java
  src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
  src/main/java/site/offload/offloadserver/db/emblem/entity/Emblem.java
  src/main/java/site/offload/offloadserver/db/emblem/entity/GainedEmblem.java
  src/main/java/site/offload/offloadserver/db/emblem/repository/GainedEmblemRepository.java
  src/main/java/site/offload/offloadserver/db/member/entity/Member.java
Labels: HOTFIX

#75 [fix] : Apple 소셜 로그인 수정 및 소셜 로그인 관련 Dto, Service 수정
  src/main/java/site/offload/offloadserver/api/member/controller/SocialLoginController.java
  src/main/java/site/offload/offloadserver/api/member/dto/request/AppleSocialLoginRequest.java
  src/main/java/site/offload/offloadserver/api/member/dto/request/GoogleSocialLoginRequest.java
  src/main/java/site/offload/offloadserver/api/member/dto/request/SocialLoginRequest.java
  src/main/java/site/offload/offloadserver/api/member/service/SocialLoginService.java
  src/main/java/site/offload/offloadserver/common/auth/SecurityConfig.java
  src/main/java/site/offload/offloadserver/external/oauth/apple/AppleFeignClient.java
  src/main/java/site/offload/offloadserver/external/oauth/apple/AppleIdentityTokenValidator.java
  src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeyGenerator.java
  src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeys.java
  src/main/java/site/offload/offloadserver/external/oauth/apple/AppleSocialLoginService.java
  src/main/java/site/offload/offloadserver/external/oauth/google/GoogleSocialLoginService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
Labels: Chore

#77 [chore] TEXT 컬럼 수정, PlaceConstants 수정
  src/main/java/site/offload/offloadserver/api/place/dto/constans/PlaceConstants.java
  src/main/java/site/offload/offloadserver/db/character/entity/Character.java
  src/main/java/site/offload/offloadserver/db/charactermotion/entity/CharacterMotion.java
Labels: 🐞 Bug, HOTFIX

#73 [setting] 칭호 데이터 넣기
  src/main/java/site/offload/offloadserver/db/emblem/entity/Emblem.java
  src/main/java/site/offload/offloadserver/db/member/entity/Member.java
Labels: Setting

#71 [fix] 얻은 캐릭터 모션 리포 생성 및 모험 정보 APi 수정
  src/main/java/site/offload/offloadserver/api/charactermotion/service/GainedCharacterMotionService.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/db/charactermotion/repository/GainedCharacterMotionRepository.java
Labels: 🐞 Bug, HOTFIX

#79 [chore] 탐험 인증 시 퀘스트 불러오기 수정
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
Labels: Chore

#81 [fix] 멤버 회원가입시 기본 칭호 GainedEmblem db에 추가
  src/main/java/site/offload/offloadserver/api/emblem/service/GainedEmblemService.java
  src/main/java/site/offload/offloadserver/api/member/service/SocialLoginService.java
  src/main/java/site/offload/offloadserver/db/emblem/entity/GainedEmblem.java
Labels: 🐞 Bug, Chore

#86 [fix] CharacerResponse dto 스택오버플로우 오류
  src/main/java/site/offload/offloadserver/api/character/dto/response/CharacterResponse.java
  src/main/java/site/offload/offloadserver/api/character/service/CharacterService.java
  src/main/java/site/offload/offloadserver/api/character/usecase/CharacterUseCase.java
  src/main/java/site/offload/offloadserver/db/character/repository/CharacterRepository.java
Labels: 🐞 Bug

#88 [chore] BaseTimeEntity, UUID -> String 수정
  src/main/java/site/offload/offloadserver/db/emblem/entity/GainedEmblem.java
  src/main/java/site/offload/offloadserver/db/place/entity/Place.java
  src/main/java/site/offload/offloadserver/db/place/entity/VisitedPlace.java
  src/main/java/site/offload/offloadserver/db/quest/entity/Quest.java
  src/main/java/site/offload/offloadserver/db/quest/entity/QuestReward.java
Labels: Chore

#94 [fix] 캐릭터 조회시 이름 반환
  src/main/java/site/offload/offloadserver/api/character/dto/response/CharacterResponse.java
  src/main/java/site/offload/offloadserver/api/character/usecase/CharacterUseCase.java
Labels: 🐞 Bug, Chore

#100 [fix] : 카테고리 이미지 추가
  src/main/java/site/offload/offloadserver/api/place/dto/response/RegisteredPlaceResponse.java
  src/main/java/site/offload/offloadserver/api/place/usecase/PlaceUsecase.java
  src/main/java/site/offload/offloadserver/db/place/entity/Place.java
Labels: Chore

#101 [fix] 모험 정보 조회 API에서 characterId 요청 이슈
  src/main/java/site/offload/offloadserver/api/character/service/CharacterService.java
  src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java
  src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java
  src/main/java/site/offload/offloadserver/api/member/dto/request/MemberAdventureInformationRequest.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/db/character/repository/CharacterRepository.java
Labels: 🐞 Bug, Refactor

#105 [fix] 회원가입시 기본 퀘스트 진행
  src/main/java/site/offload/offloadserver/api/exception/GlobalExceptionHandler.java
  src/main/java/site/offload/offloadserver/api/message/CustomErrorCode.java
  src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
  src/main/java/site/offload/offloadserver/api/quest/service/QuestService.java
  src/main/java/site/offload/offloadserver/api/quest/usecase/QuestUseCase.java
Labels: 🐞 Bug, Chore

#106 [fix] : readme 수정
  README.md
Labels: Docs

#109 [fix] 캐릭터 선택 이후 스포트라이트 이미지 반환
  src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java
  src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java
  src/main/java/site/offload/offloadserver/api/member/dto/response/ChooseCharacterResponse.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/db/character/entity/Character.java
Labels: 🐞 Bug, Feature, Refactor

#110 [hotfix] : 모션보상 관련 퀘스트 일부 저장
  src/main/java/site/offload/offloadserver/api/charactermotion/service/GainedCharacterMotionService.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/api/quest/service/CompleteQuestService.java
  src/main/java/site/offload/offloadserver/api/quest/service/ProceedingQuestService.java
  src/main/java/site/offload/offloadserver/api/quest/service/QuestRewardService.java
  src/main/java/site/offload/offloadserver/db/charactermotion/entity/GainedCharacterMotion.java
  src/main/java/site/offload/offloadserver/db/quest/embeddable/RewardList.java
  src/main/java/site/offload/offloadserver/db/quest/entity/CompleteQuest.java
  src/main/java/site/offload/offloadserver/db/quest/entity/QuestReward.java
  src/main/java/site/offload/offloadserver/db/quest/repository/CompleteQuestRepository.java
  src/main/java/site/offload/offloadserver/db/quest/repository/ProceedingQuestRepository.java
  src/main/java/site/offload/offloadserver/db/quest/repository/QuestRewardRepository.java
Labels: Chore, HOTFIX

#112 fix: 탐험 인증 API 수정
  src/main/java/site/offload/offloadserver/api/charactermotion/service/GainedCharacterMotionService.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/api/quest/service/ProceedingQuestService.java
  src/main/java/site/offload/offloadserver/api/quest/service/QuestRewardService.java
  src/main/java/site/offload/offloadserver/common/util/DistanceUtil.java
  src/main/java/site/offload/offloadserver/db/place/entity/Place.java
  src/main/java/site/offload/offloadserver/db/place/entity/PlaceCategory.java
  src/main/java/site/offload/offloadserver/db/quest/embeddable/RewardList.java
  src/main/java/site/offload/offloadserver/db/quest/entity/ProceedingQuest.java
  src/main/java/site/offload/offloadserver/db/quest/repository/QuestRewardRepository.java
  src/main/resources/application-dev.yaml
  src/main/resources/db/data.sql
  src/test/java/site/offload/offloadserver/integration/IntegrationTest.java
Labels: 🐞 Bug

#114 [fix] : 기존 유저 판별 필드 추가
  src/main/java/site/offload/offloadserver/api/member/controller/SocialLoginController.java
  src/main/java/site/offload/offloadserver/api/member/controller/SocialLoginControllerSwagger.java
  src/main/java/site/offload/offloadserver/api/member/dto/response/SocialLoginResponse.java
  src/main/java/site/offload/offloadserver/api/member/usecase/SocialLoginUseCase.java
Labels: Refactor, Chore

#117 [fix] : 기존 유저 판별 필드 추가
  src/main/java/site/offload/offloadserver/api/member/service/MemberService.java
  src/main/java/site/offload/offloadserver/api/member/usecase/SocialLoginUseCase.java
  src/main/java/site/offload/offloadserver/db/member/entity/Member.java
  src/main/java/site/offload/offloadserver/db/member/repository/MemberRepository.java
  src/main/java/site/offload/offloadserver/external/oauth/apple/AppleSocialLoginService.java
  src/main/java/site/offload/offloadserver/external/oauth/google/GoogleSocialLoginService.java
  src/main/resources/application-local.yaml
Labels: Chore

#118 [feat] 위치 정보 대조 API 생성
  src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java
  src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java
  src/main/java/site/offload/offloadserver/api/member/dto/request/AuthPositionRequest.java
  src/main/java/site/offload/offloadserver/api/member/dto/response/AuthAdventureResponse.java
  src/main/java/site/offload/offloadserver/api/member/dto/response/VerifyPositionDistanceResponse.java
  src/main/java/site/offload/offloadserver/api/member/dto/response/VerifyQrcodeResponse.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/db/character/entity/Character.java
Labels: 🐞 Bug, Feature

#119 [fix] 조건문 수정
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
Labels: 🐞 Bug, Chore

#120 [chore] 프로필 업데이트 생년월일 타입 수정
  src/main/java/site/offload/offloadserver/api/member/dto/request/MemberProfileUpdateRequest.java
  src/main/java/site/offload/offloadserver/db/member/embeddable/Birthday.java
Labels: 🐞 Bug, Chore

#121 [feat] 보상 추가 및 setec 세팅
  src/main/java/site/offload/offloadserver/api/member/dto/request/MemberProfileUpdateRequest.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/db/emblem/entity/Emblem.java
  src/main/java/site/offload/offloadserver/db/quest/embeddable/RewardList.java
Labels: Feature, HOTFIX

#122 [chore] member 엔티티 필드수정
  src/main/java/site/offload/offloadserver/db/member/entity/Member.java
Labels: 🐞 Bug, HOTFIX

#123 [hotfix] : presignUrl 변환
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/external/aws/S3UseCase.java
Labels: 🐞 Bug, HOTFIX

#125 [fix] : 캐릭터 조회 시 캐릭터 선택 이미지 반환
  src/main/java/site/offload/offloadserver/api/character/usecase/CharacterUseCase.java
  src/main/java/site/offload/offloadserver/db/character/entity/Character.java
Labels: Chore

#127 [fix] 탐험정보 조회 모션이미지 기본이미지 둘다 반환
  src/main/java/site/offload/offloadserver/api/member/dto/response/MemberAdventureInformationResponse.java
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/common/jwt/JwtTokenProvider.java
Labels: Refactor, Chore

#128 [chore] 탐험 실패 시 이미지 반환
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
  src/main/java/site/offload/offloadserver/db/character/entity/Character.java
Labels: 🐞 Bug, Chore

#132 [fix] 퀘스트 추가
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
Labels: 🐞 Bug, HOTFIX

#133 [fix] 탐험 인증 시 퀘스트 클리어 카운트 증가 문제
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
Labels: 🐞 Bug, Chore

#136 [feat] sentry 전송 코드 추가
  src/main/java/site/offload/offloadserver/api/exception/GlobalExceptionHandler.java
Labels: 🐞 Bug, Setting

#138 [chore] 오차 수정
  src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
Labels: Chore

#142 [fix] 애플 로그인 에러 수정
  offroad-api/src/main/java/site/offload/api/member/usecase/SocialLoginUseCase.java
Labels: 🐞 Bug

#155 fix: Component Scan db module 추가
  offroad-api/src/main/java/site/offload/api/OffloadserverApiApplication.java
Labels: 🐞 Bug

#158 fix: 닉네임, 캐릭터 선택 여부에 따른 모험 정보 조회 api 반환값 수정
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
Labels: 🐞 Bug
