Repository Team-Offroad/Offroad-server, pull requests merged in 2024-09, with the labels that each got.

#195 [refactor] : 캐릭터 아이디 철자 수정 및 약관 동의 여부 저장
  offroad-api/src/main/java/site/offload/api/member/controller/MemberController.java
  offroad-api/src/main/java/site/offload/api/member/controller/MemberControllerSwagger.java
  offroad-api/src/main/java/site/offload/api/member/dto/request/TermsAgreeRequest.java
  offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharacterResponse.java
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
  offroad-api/src/main/resources/application-local.yaml
  offroad-api/src/test/java/site/offload/api/member/usecase/MemberUseCaseTest.java
  offroad-db/src/main/java/site/offload/db/member/entity/MemberEntity.java
  offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java
Labels: Chore

#200 [fix] : 캐릭터 조회 API에 대표 캐릭터 ID 추가
  offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharactersResponse.java
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
Labels: Chore

#203 chore: 공원 인증 범위 수정
  offroad-api/src/main/java/site/offload/api/member/usecase/AuthAdventureUseCase.java
Labels: Chore

#204 chore: 공원 탐험 인증 범위 수정
  offroad-api/src/main/java/site/offload/api/member/usecase/AuthAdventureUseCase.java
Labels: Chore

#205 chore: 토큰 유효시간 수정
  offroad-api/src/main/java/site/offload/api/auth/jwt/JwtTokenProvider.java
Labels: Chore

#207 fix: 장소 조회 API 응답데이터 수정
  offroad-api/src/main/java/site/offload/api/place/dto/response/RegisteredPlaceResponse.java
  offroad-api/src/main/java/site/offload/api/place/usecase/PlaceUseCase.java
Labels: 🐞 Bug

#208 chore: 홈화면 모션캡쳐이미지 반환 추가
  offroad-api/src/main/java/site/offload/api/member/dto/response/MemberAdventureInformationResponse.java
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
Labels: Chore

#213 refactor: swagger 문서 정보 추가
  offroad-api/src/main/java/site/offload/api/character/controller/CharacterControllerSwagger.java
  offroad-api/src/main/java/site/offload/api/coupon/controller/CouponControllerSwagger.java
  offroad-api/src/main/java/site/offload/api/emblem/controller/EmblemControllerSwagger.java
  offroad-api/src/main/java/site/offload/api/member/controller/MemberControllerSwagger.java
  offroad-api/src/main/java/site/offload/api/member/controller/TokenControllerSwagger.java
  offroad-api/src/main/java/site/offload/api/quest/controller/QuestControllerSwagger.java
Labels: Refactor

#217 [feat] : 공지사항 목록 조회 API 구현
  offroad-api/src/main/java/site/offload/api/announcement/controller/AnnouncementController.java
  offroad-api/src/main/java/site/offload/api/announcement/controller/AnnouncementControllerSwagger.java
  offroad-api/src/main/java/site/offload/api/announcement/dto/response/AnnouncementDetailResponse.java
  offroad-api/src/main/java/site/offload/api/announcement/dto/response/AnnouncementsResponse.java
  offroad-api/src/main/java/site/offload/api/announcement/service/AnnouncementService.java
  offroad-api/src/main/java/site/offload/api/announcement/usecase/AnnouncementUseCase.java
  offroad-db/src/main/java/site/offload/db/announcement/entity/AnnouncementEntity.java
  offroad-db/src/main/java/site/offload/db/announcement/repository/AnnouncementRepository.java
  offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java
Labels: Feature

#219 fix: 신규 획득 여부가 바뀌지 않는 오류 수정
  offroad-api/src/main/java/site/offload/api/charactermotion/usecase/CharacterMotionUseCase.java
  offroad-api/src/main/java/site/offload/api/coupon/usecase/CouponListUseCase.java
  offroad-api/src/main/java/site/offload/api/emblem/usecase/EmblemUseCase.java
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
Labels: 🐞 Bug

#222 chore: 구역 enum에 별칭 추가
  offroad-api/src/main/java/site/offload/api/place/dto/response/RegisteredPlaceResponse.java
  offroad-api/src/main/java/site/offload/api/place/usecase/PlaceUseCase.java
  offroad-enum/src/main/java/site/offload/enums/place/PlaceArea.java
Labels: Chore

#226 fix: 장소에 없는 쿠폰사용코드 체크 수정
  offroad-api/src/main/java/site/offload/api/coupon/usecase/CouponApplyUseCase.java
  offroad-api/src/main/java/site/offload/api/place/service/PlaceService.java
  offroad-api/src/test/java/site/offload/api/place/service/PlaceEntityServiceTest.java
  offroad-db/src/main/java/site/offload/db/place/repository/PlaceRepository.java
Labels: 🐞 Bug

#227 chore: 마이페이지 캐릭터 이미지 추가
  offroad-api/src/main/java/site/offload/api/member/dto/response/UserInfoResponse.java
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
Labels: Chore

#228 fix: 반환 캐릭터 이미지 presign url 추가
  offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
Labels: 🐞 Bug

#229 chore: 쿠폰 리스트 응답값 수정
  offroad-api/src/main/java/site/offload/api/coupon/dto/AvailableCouponResponse.java
  offroad-api/src/main/java/site/offload/api/coupon/usecase/CouponListUseCase.java
  offroad-api/src/test/java/site/offload/api/coupon/usecase/CouponApplyUseCaseTest.java
  offroad-api/src/test/java/site/offload/api/coupon/usecase/CouponListUseCaseTest.java
  offroad-api/src/test/java/site/offload/api/place/service/PlaceEntityServiceTest.java
Labels: Chore
